language: node_js
node_js:
  - "6"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
before_script:
  - ./node_modules/.bin/sequelize --env test db:create db:migrate
env:
  - DB_ENV_POSTGRESQL_DB=scale_of_belief DB_ENV_POSTGRESQL_USER=postgres
