language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_modules
services:
  - postgresql
before_script:
  - ./node_modules/.bin/sequelize --env test db:create
  - ./node_modules/.bin/sequelize --env test db:migrate
script:
  - ./node_modules/.bin/standard
  - ./node_modules/.bin/jest --forceExit --coverage
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
env:
  - DB_ENV_POSTGRESQL_DB=scale_of_belief DB_ENV_POSTGRESQL_USER=postgres
addons:
  postgresql: "9.4"
