swagger: "2.0"
info:
  title: Scale of Belief - Content Score API
  description: API to allow scoring content for placement on the scale of belief.
  version: 1.0.0

consumes:
  - application/json

produces:
  - application/json

schemes:
  - https
  - http

basePath: /api

tags:
  - name: score
    description: Content Scoring

paths:
  /score:
    get:
      summary: Get single content score by uri
      tags:
        - score
      parameters:
        - name: uri
          description: Content URI
          in: query
          required: true
          type: string
          format: uri
      security:
        - ApiKeyAuth: []
        - JwtAuth: []
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ContentScore'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          $ref: '#/responses/NotFound'
    post:
      summary: Create or Update a content score
      tags:
        - score
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          description: Set or update scores for a content uri
          schema:
            $ref: '#/definitions/ContentScore'
      security:
        - ApiKeyAuth: []
        - JwtAuth: []
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ContentScore'
        400:
          $ref: '#/responses/BadRequest'
        401:
          $ref: '#/responses/Unauthorized'
  /scores:
      get:
        summary: Get multiple content scores by uri prefix.
        tags:
          - score
        parameters:
          - name: uri
            description: Content URI prefix
            in: query
            required: true
            type: string
            format: uri
        security:
          - ApiKeyAuth: []
          - JwtAuth: []
        responses:
          200:
            description: OK
            schema:
              type: array
              items:
                $ref: '#/definitions/ContentScore'
          401:
            $ref: '#/responses/Unauthorized'
          404:
            $ref: '#/responses/NotFound'
  /api-users:
    get:
      summary: Get API Users
      tags:
        - users
      security:
        - ApiKeyAuth: []
        - JwtAuth: []
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/ApiUser'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          $ref: '#/responses/NotFound'
  /api-user:
    get:
      summary: Get single API User score by guid
      tags:
        - users
      parameters:
        - name: guid
          description: guid
          in: query
          required: true
          type: string
          pattern: '^(\{{0,1}([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){12}\}{0,1})$'
      security:
        - ApiKeyAuth: []
        - JwtAuth: []
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ApiUser'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          $ref: '#/responses/NotFound'
    post:
      summary: Create or Update an API user
      tags:
        - users
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          description: Create or update an API user
          schema:
            $ref: '#/definitions/ApiUser'
      security:
        - ApiKeyAuth: []
        - JwtAuth: []
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ApiUser'
        400:
          $ref: '#/responses/BadRequest'
        401:
          $ref: '#/responses/Unauthorized'
  /content:
    get:
      summary: List known content URIs that are missing scores, narrow the list by content URI prefix
      tags:
        - content
      parameters:
        - name: uri
          description: Content URI prefix
          in: query
          type: string
          format: uri
      security:
        - ApiKeyAuth: []
        - JwtAuth: []
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              description: Content URI
              type: string
              format: uri
        401:
          $ref: '#/responses/Unauthorized'
  /login:
    get:
      summary: Testing
      tags:
        - login
      parameters:
        - name: ticket
          description: Service ticket
          in: query
          type: string
      security: []
      responses:
        200:
          description: OK
          schema:
            type: string
    post:
      summary: Login to the API
      tags:
        - login
      parameters:
        - name: body
          in: body
          description: Login credentials
          schema:
            $ref: '#/definitions/Credentials'
      security: []
      responses:
        200:
          description: OK
          schema:
            type: string
        401:
          $ref: '#/responses/Unauthorized'

securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    name: X-Api-Key
    in: header
    x-authorize: 'security/api-key-authorize.js'
  JwtAuth:
    type: apiKey
    name: Authorization
    in: header
    x-authorize: 'security/jwt-authorize.js'

responses:
  NotFound:
    description: The specified resource was not found
    schema:
      $ref: '#/definitions/Error'
  Unauthorized:
    description: Unauthorized to perform the request
    schema:
      $ref: '#/definitions/Error'
  BadRequest:
    description: The request contained bad data
    schema:
      $ref: '#/definitions/Error'

definitions:
  ContentScore:
    type: object
    properties:
      uri:
        type: string
        format: uri
      score:
        $ref: '#/definitions/Score'
  ApiUser:
      type: object
      properties:
        guid:
          type: string
          format: guid
        api_pattern:
          type: array
          items:
            type: string
        contact_email:
          type: string
          format: email
        type:
          type: string
  Score:
    type: object
    properties:
      unaware:
        type: integer
        minimum: 1
        maximum: 5
      curious:
        type: integer
        minimum: 1
        maximum: 5
      follower:
        type: integer
        minimum: 1
        maximum: 5
      guide:
        type: integer
        minimum: 1
        maximum: 5
      confidence:
        type: integer
        minimum: 0
        maximum: 100
    required:
      - unaware
      - curious
      - follower
      - guide
      - confidence
  Credentials:
    type: object
    properties:
      ticket:
        type: string
    required:
      - ticket
  Error:
    type: object
    properties:
      message:
        type: string
    required:
      - error
